### ISSUE TITLE
Notebook in tests have failing cells

### ISSUE THREAD

**Issue by koldunovn** [ruiying-ocean/cgeniepy#2]
This is notebook in question: https://github.com/ruiying-ocean/cgeniepy/blob/master/test/test.ipynb . It it probably also related to #1 

openjournals/joss-reviews#6762

**Comment by koldunovn** [comment]
Also `seaborn` is necessary for the notebook to work, but it is not in the requirements of the package.

**Comment by koldunovn** [comment]
`LGM_d13c_CLEAN.txt` file references in the notebook is nowhere to be found.

**Comment by koldunovn** [comment]
All paths in the notebook are absolute and point to author's directory. Please, at least define something like base path:
```
base_path='/Users/yingrui/Science/lgm_foram_niche/model/'
```
and use it for providing paths to the data.

Also, please, add instructions on how to download the data. I general, user should be able to just execute the cells and get the results, without too much additional editing of the notebook.

**Comment by ruiying-ocean** [comment]
This file is not meant to be uploaded. I use it to do some quick tests. Seaborn is not necessary for the package function per se.
So I will just remove this file and update the download instructions as #1.
