### ISSUE TITLE
Several tests are failing

### ISSUE THREAD

**Issue by koldunovn** [ruiying-ocean/cgeniepy#3]
I tried to run pytest on the code, and several tests are failing:
<img width="309" alt="Screenshot 2024-09-14 at 14 37 21" src="https://github.com/user-attachments/assets/2d9ce72b-729e-419f-bb00-4a390ed96a05">

There is also no automatic tests running on PR (with GitHub Actions), I think it would be worth to add them. Failing tests most probably related to #1  - so ether having sample dataset as part of the repository, or provide link to where download sample data would be great.
   
openjournals/joss-reviews#6762

**Comment by ruiying-ocean** [comment]
The package test is updated and a local result is as below

<img width="994" alt="image" src="https://github.com/user-attachments/assets/ba2ca0cb-188b-4018-845e-3f1d2b1812c2">

**Comment by koldunovn** [comment]
Confirm.
